name: base
channels:
  - default
  - conda-forge
dependencies:
  - numpy
  - pandas
  - flask
  - dask
  - distributed
  - joblib
  - cython
  - numba
  - pip
  - feather-format
  - matplotlib
  - seaborn
  - pep8
  - scikit-learn
  - scikit-image
  - nose
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - jupyter_core
  - jupyter_highlight_selected_word
  - jupyter_nbextensions_configurator
  - jupyterlab
  - jupyterlab_launcher
  - nodejs
  - ipykernel
  - nb_conda_kernels
  - tensorflow
  - keras
  - ipython
  - xlrd
  - fastparquet
  - pystan
  - fbprophet
  - scipy
  - bottleneck
  - networkx=1.11
  - widgetsnbextension
  - ipywidgets
