name: base
channels:
  - default
  - anaconda
dependencies:
  - numpy
  - pandas
  - flask
  - dask
  - distributed
  - joblib
  - cython
  - numba
  - matplotlib
  - seaborn
  - pep8
  - scikit-learn
  - scikit-image
  - nose
  - nodejs
  - ipython
  - ipywidgets
  - xlrd
  - fastparquet
  - scipy
  - bottleneck
  - gcc
  - libgcc