name: base
channels:
  - default
dependencies:
  - numpy
  - pandas
  - flask
  - dask
  - distributed
  - joblib
  - cython
  - numba
  - matplotlib
  - seaborn
  - pep8
  - scikit-learn
  - scikit-image
  - nose
  - jupyter
  - jupyterlab
  - nodejs
  - ipykernel
  - ipython
  - xlrd
  - fastparquet
  - scipy
  - bottleneck
  - widgetsnbextension
  - ipywidgets
  - gcc

